#! /bin/bash

curl -v --http2-prior-knowledge \
  -XQUERY \
  -H"database: postgres" \
  -H"dbhost: paris-scw-01.influent.cc" \
  -H"dbport: 65432" \
  -H"user: user2(md5)" \
  -H"password: YzQzOGI2MmNiN2Vm" \
  "http://localhost:8080/"